---
apiVersion: "v1"
data:
  fabric8-default-environments: "Testing=${namespace}-testing,Staging=${namespace}-staging,Production=${namespace}-prod"
  jenkins-gogs-email: "gogsadmin@fabric8.local"
  jenkins-gogs-password: "RedHat$1"
  jenkins-gogs-user: "gogsadmin"
  jenkins-workflow-git-repository: "https://github.com/fabric8io/jenkins-workflow-library.git"
kind: "ConfigMap"
metadata:
  annotations:
    fabric8.fabric8-forge/summary: "Fabric8 :: Forge"
    description: "Fabric8 :: Forge"
    fabric8.fabric8-forge/iconUrl: "https://cdn.rawgit.com/fabric8io/fabric8-forge/master/fabric8-forge/src/main/fabric8/icon.svg"
    fabric8.io/json-schema: "{\n  \"type\" : \"object\",\n  \"properties\" : {\n \
      \   \"jenkins-gogs-email\" : {\n      \"type\" : \"string\",\n      \"description\"\
      \ : \"The email address of the Jenkins user on Gogs\",\n      \"default\" :\
      \ \"gogsadmin@fabric8.local\"\n    },\n    \"fabric8-default-environments\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The list of default\
      \ environment names to actual kubernetes namespaces\",\n      \"default\" :\
      \ \"Testing=${namespace}-testing,Staging=${namespace}-staging,Production=${namespace}-prod\"\
      \n    },\n    \"jenkins-gogs-password\" : {\n      \"type\" : \"string\",\n\
      \      \"description\" : \"The password for Jenkins to login to Gogs\",\n  \
      \    \"default\" : \"RedHat$1\"\n    },\n    \"jenkins-gogs-user\" : {\n   \
      \   \"type\" : \"string\",\n      \"description\" : \"The user name for Jenkins\
      \ to login to Gogs\",\n      \"default\" : \"gogsadmin\"\n    },\n    \"jenkins-workflow-git-repository\"\
      \ : {\n      \"type\" : \"string\",\n      \"description\" : \"The git clone\
      \ URL for the jenkins workflow repository which can be reused across projects\"\
      ,\n      \"default\" : \"https://github.com/fabric8io/jenkins-workflow-library.git\"\
      \n    }\n  }\n}"
  labels: {}
  name: "fabric8-forge"
